### PR TITLE
fix: editing verified relics

### LINKED ISSUE #224: [Bug] Editing verified relics should nullify their verified status
### Repro steps

* Import relics from Archiver / Relic scorer
* Edit a verified relic's substats and then save
* The relic still remains verified

### Objective

Once edited they should lose their verified status, until verified again. This is because verified relics are the ones that should always match the actual ingame value

### PR DESCRIPTION
**Pull request by FI00ds**
# Pull Request

## Description

* Removes verified status from relics when edited

## Related Issue

* Closes #224 

## Checklist

- [x] I have added commit messages that are descriptive and meaningful.
- [x] I have tested the changes locally.
- [x] I have reviewed the code changes.

### CODE REVIEW

File: src/components/RelicModal.tsx [hunk 1]
```diff
@@ -208,6 +208,22 @@ export default function RelicModal(props: {
...
+      substatType0: relicForm.getFieldValue('substatType0'),
+      substatValue0: relicForm.getFieldValue('substatValue0'),
+      substatType1: relicForm.getFieldValue('substatType1'),
+      substatValue1: relicForm.getFieldValue('substatValue1'),
+      substatType2: relicForm.getFieldValue('substatType2'),
+      substatValue2: relicForm.getFieldValue('substatValue2'),
+      substatType3: relicForm.getFieldValue('substatType3'),
+      substatValue3: relicForm.getFieldValue('substatValue3'),
+    }
+    if (compareRelics(props.selectedRelic, currentValue)) props.selectedRelic.verified = false
```
Comment (fribbels) [inline src/components/RelicModal.tsx:226]: This feels like the wrong place to do this check, this should happen after the validation but before the relic is saved to the DB

For example, if we edit a valid verified relic, make an invalid change, this would show an error "Substats are invalid/etc", not make the change, but still unverify the relic.

`relicForm.submit()` should trigger the `onFinish` function and I think right before `console.log('Completed relic', relic)` is probably the right place

**Comment by fribbels** [comment]
Rethinking the requirements here, what do you think about potentially only setting it to unverified if speed is changed?

**Comment by fribbels** [comment]
I guess technically people could type in the wrong upgrade

File: src/components/RelicModal.tsx [hunk 2]
```diff
@@ -208,6 +211,26 @@ export default function RelicModal(props: {
...
+      substatType2: relicForm.getFieldValue('substatType2'),
+      substatValue2: relicForm.getFieldValue('substatValue2'),
+      substatType3: relicForm.getFieldValue('substatType3'),
+      substatValue3: relicForm.getFieldValue('substatValue3'),
+    }
+    if (compareRelics(props.selectedRelic, currentValue)) {
+      if (props.selectedRelic.verified) setHasChanged(true)
+      props.selectedRelic.verified = false
+      console.log('Relic unverified')
+    } else (setHasChanged(false))
```
Comment (fribbels) [inline src/components/RelicModal.tsx:233]: I think this is probably overcomplicating things, we dont need a state to track the status if we use the finalized relics to set the verified state in `onFinish`

File: src/components/RelicModal.tsx [hunk 3]
```diff
@@ -440,3 +463,40 @@ function SubstatInput(props: { index: number; upgrades: RelicUpgradeValues[]; re
...
+  if (initial.substatType0 != final.substatType0) return true
+  if (initial.substatValue0 != final.substatValue0) return true
+  if (initial.substatType1 != final.substatType1) return true
+  if (initial.substatValue1 != final.substatValue1) return true
+  if (initial.substatType2 != final.substatType2) return true
+  if (initial.substatValue2 != final.substatValue2) return true
+  if (initial.substatType3 != final.substatType3) return true
+  if (initial.substatValue3 != final.substatValue3) return true
+  return false
+}
```
Comment (fribbels) [inline src/components/RelicModal.tsx:502]: We have a Util that does this sort of calculation `Utils.objectHash`, which can just convert these into hash comparisons. 

Also probably bad practice to compare stats with a render function, if we ever change how stats are rendered then that may break relic comparisons.
