### PR TITLE
fix: accurately count permutations after set filters (#1482)

### LINKED ISSUE #1482: [Bug] Permutation display overestimates possible permutations
## Steps to Reproduce

1. Load a save file where all relics of set A are below level N
2. Set the minimum enhance to level N (e.g. if all relics of set A are below level 9, set the minimum enhance to 9)
3. Set the relic filters to only require 2pc of set A
## Expected Behavior

The permutation calculation should realize that there are no possible valid permutations and display the total permutations as being 0.

## Actual Behavior

The permutation calculation does not filter out permutations that do no pass the 2+any requirement, and therefore displays a large number of possible permutations.

### PR DESCRIPTION
**Pull request by r3xsean**
# Pull Request

## Description

Fixes the permutation display overcount reported in #1482. The sidebar "Perms" count was the naive slot product (`|Head| * |Hands| * |Body| * |Feet| * |Sphere| * |Rope|`), which ignores multi-piece set constraints. When a 2+Any filter widened the per-slot allow-list but the 2pc-of-setA requirement could not be met (e.g. all set-A relics below the min enhance threshold), the displayed count showed billions while the real valid permutation count was far smaller or zero. Reporter confirmed "138bil / 7bil" on their setup.

**Added**

- `countsBySet` return on `getFilteredRelicCounts`: per-slot per-set buckets of the filtered relic pool, respecting locked-parts semantics.
- `computeValidPermutationCount` / `computeValidPermutationParts` in `relicSetSolver`: sum the slot product over the (head, hands, body, feet) tuples the relic set solver marks valid, times the valid (sphere, rope) sum. The parts variant returns relic and ornament sums separately.
- `permutationsNaive` field on the optimizer display store, set alongside `permutations`. The sidebar "Perms" shows the valid count; the `ManyPermsModal` CPU-work warning gates on the naive product since runtime still scales with the naive index space the worker iterates.
- 13 unit tests covering 4pc, 2+Any, 2+2, zero-slot, min-enhance exclusion, locked-relic-not-found, ornament pair infeasibility, store defaults and setters, and the suggestions engine branch for both relic and ornament infeasibility.

**Changed**

- `recalculatePermutations` and `optimize()` now compute the valid count via the set solver and write both valid and naive totals to the store.
- `permutationsSearched` updates in the CPU (`optimizer.ts`) and GPU (`webgpuOptimizer.ts`) paths are scaled by `validPermutations / naiveProduct` so the progress bar fraction remains consistent with the displayed total.
- `detectZeroPermutationCauses` now detects set-constraint infeasibility (split into relic vs ornament) so a user whose slots are all non-empty but whose filter combination is unsatisfiable gets the correct `RELIC_SETS` or `ORNAMENT_SETS` fix suggestion instead of falling through to `IMPORT`.

**Fixed**

- Sidebar "Perms" number now reflects the true number of permutations that satisfy all active set constraints.
- Zero-permutation modal now diagnoses set-filter infeasibility correctly.

## Related Issue

Closes #1482

## Checklist

- [x] I have added commit messages that are descriptive and meaningful.
- [x] I have tested the changes locally.
- [x] I have reviewed the code changes.

## Screenshots

N/A (behavior change on a count display; verified via unit tests and browser smoke check).

### CODE REVIEW

File: src/lib/gpu/webgpuOptimizer.ts [hunk 1]
```diff
@@ -38,11 +38,15 @@ export async function gpuOptimize(props: {
...
+  validPermutations: number,
   computeEngine: string,
   relicSetSolutions: number[],
   ornamentSetSolutions: number[],
 }) {
-  const { context, request, relics, permutations, computeEngine, relicSetSolutions, ornamentSetSolutions } = props
+  const { context, request, relics, permutations, validPermutations, computeEngine, relicSetSolutions, ornamentSetSolutions } = props
+  // searched counts in the naive index space; scale to valid-permutation space for display (#1482).
+  const progressScale = permutations > 0 ? validPermutations / permutations : 0
+  const scaleSearched = (naiveSearched: number): number => Math.min(validPermutations, Math.round(naiveSearched * progressScale))
```
Comment (fribbels) [inline src/lib/gpu/webgpuOptimizer.ts]: This permutation scaling / approximation behavior concerns me as a UX regression, not convinced on this approach over providing an accurate count from the worker. This leads to scenarios where users can get misleading ETAs or being stuck towards the end of searches (think of how some loading bars can get stuck at 99% from approximations) in cases where relic ordering causes invalid set combos to not be evenly distributed.

This is actually a harder problem than it seems for the GPU side. On the CPU side its as easy as a counter++ at the set filter. But in the GPU optimizer you would need to add an atomic counter across all threads, or come up with ways to count the valid permutations per dispatch, been thinking about these for a couple days and I might have some better solutions, happy to follow up on discord

File: src/lib/tabs/tabOptimizer/suggestionsEngine.ts [hunk 2]
```diff
@@ -131,14 +136,33 @@ export const ZeroPermRootCauseFixes = {
...
+  // Set-constraint infeasibility: every slot has relics but no valid 4-tuple /
+  // ornament pair satisfies the filter (issue #1482). Per-slot counts can't see
+  // this, so consult the set solver directly. Split relic vs ornament so the
+  // right fix is suggested (clearing relic sets vs ornament sets).
+  const allSlotsNonEmpty = counts.Head > 0 && counts.Hands > 0
+    && counts.Body > 0 && counts.Feet > 0
+    && counts.PlanarSphere > 0 && counts.LinkRope > 0
+  let relicSetInfeasible = false
+  let ornamentSetInfeasible = false
+  if (allSlotsNonEmpty && (request.relicSets.length > 0 || request.ornamentSets.length > 0)) {
```
Comment (fribbels) [inline src/lib/tabs/tabOptimizer/suggestionsEngine.ts]: Bug in the condition here, the allSlotsNonEmpty check is too restrictive, relicSetInfeasible and ornamentSetInfeasible are independent of each other, you can have one pass and the other fail and the compound condition skips computeValidPermutationParts entirely. E.g. you might miss RELIC_SETS / ORNAMENT_SETS a cause. + test case for those

File: src/lib/optimization/optimizer.ts [hunk 3]
```diff
@@ -326,9 +359,14 @@ export const Optimizer = {
           const resultArr = new Float32Array(result.buffer)
           BufferPacker.extractArrayToResults(resultArr, run.runSize, queueResults, taskInput.skip, gridSortColumn)
 
+          // permutationsSearched is rescaled into the valid-permutation space so
+          // searched/permutations stays meaningful for the progress bar (issue #1482).
+          // Worker still iterates the naive index space; valid tuples are approximately
+          // uniformly distributed, so this is accurate at completion and monotonic
+          // during.
```
Comment (fribbels) [inline src/lib/optimization/optimizer.ts]: Generally would recommend cleaning up these ultra verbose comments, there's 16 comments referencing Issue # 1482, a lot of these are repetitive
